baseURL: "https://Exorcistee.github.io/resume/"
title: Resume
copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
paginate: 5
theme: [hugo-PaperMod]
